GlobalNOC/globalnoc-networkmap-panel

src/editor.html
under the options tab in edit, this fix only shows the "-" button on the last entry
=> fixed layer addition remove button

package.json, src/atlas3.js, src/css/NetworkLayer.css, src/css/TrafficLayer.css, src/display_editor.html, src/editor.html, src/js/map/BaseMap.js, src/js/map/LeafletMap.js, src/js/map/NetworkLayer.js, src/js/map/SingleTubeLayer.js, src/js/widget/InfoDiv.js, src/js/widget/Legend.js, src/scale.js
This commit adds a "Save" button functionality and removes the "Copy to clipboard" option
=> Json editor changes

gulpfile.js, src/atlas3.js, src/display_editor.html, src/editor.html, src/js/util/Topology.js, src/js/widget/Legend.js, src/json_editor.html, src/scale.js
This Pull-request adds the following: 
- Modal JSON editor
- Ability to allow circuits without endpoints and vice-versa
- Minor UI changes to the options tab
- Disable invert legend in threshold mode
- Ability to select color criteria for nodes
- Bug fixes include: numbering for spectrum legend, to si bug caused by removing default tooltip
=> Changes to Options Tab and Display Tab

src/atlas3.js, src/js/map/LeafletMap.js, src/partials/editor.html
This PR adds logical map feature to network map panel. Closes #31
=> Logical map

src/atlas3.js, src/js/map/LeafletMap.js, src/partials/editor.html, src/partials/module.html
Dynamic links size merged with twin tubes code
=> Dynamic links size merged with twin tubes code

src/atlas3.js, src/js/map/NetworkLayer.js
=> Tooltip add current

package.json
=> Updating lodash to v4.17.5

src/js/map/SingleTubeLayer.js, src/js/map/TwinTubeLayer.js
This closes issue #28 
In addition, the ability to display labels above endpoints has been added.
=> Added shapes to use as endpoint markers and labels for the endpoints

src/atlas3.js, src/js/map/LeafletMap.js, src/js/widget/InfoDiv.js, src/js/widget/Legend.js
=> Fixing logical map flicker issue and legend number label colors

src/js/map/SingleTubeLayer.js, src/js/map/TwinTubeLayer.js
Unified non-circles under the SVG Polygon tag, allowing for more uniform scaling and behavior of node shapes. Additionally, default values have been set for sizing and variables added for ease of changing the defaults. This was done as a response to debugging node shape scaling and defaults.
=> Node Marker Scaling and Code Reduction

src/atlas3.js, src/partials/json_editor.html
Resolves Issue #61
Fixed saving issues with JSON Editor. 
Added button for Save & Exit to JSON Editor.
=> JSON Editor Saving: Issue #61

CHANGES.md, Makefile, grnoc-grafana-worldview.spec, package.json, src/plugin.json
Updated files for the release of Networkmap Panel v1.0.6
=> Moving to v1.0.6

gulpfile.js, src/css/NetworkLayer.css, src/js/widget/InfoDiv.js
commit e53bb60 Fixes partly #25 (Image links still appear broken)
commit 4658739 Fixes #57
=> Bug Fixes 

src/plugin.json
=> Fixing readme for the plugin on grafana

src/js/map/SingleTubeLayer.js, src/js/map/TwinTubeLayer.js, src/js/util/Topology.js
Applies default node color only when there's no query for nodes.
=> Fixing node color bug when node has data.

src/js/util/Topology.js, src/scale.js
The nodes were not properly displayed on the map. The issue should be fixed now.
=> Nodes bug Fix.

Makefile, grnoc-grafana-worldview.spec, package.json, src/atlas3.js, src/partials/display_editor.html, src/plugin.json, src/scale.js
* Updated `<spectrum-picker>` to `<color-picker>` to fix issues in Grafana v6
* Fixed issue with map rendering
* Prepping for v1.1.1
=> Updates for grafana v6

src/atlas3.js
=> Adding a delay to first render to fix map rendering issues in Grafana v6.3.x

src/js/util/Topology.js
=> Fix endpoint matching

package-lock.json, package.json, src/atlas3.js, src/js/map/LeafletMap.js, src/js/map/SingleTubeLayer.js, src/partials/editor.html, src/plugin.json
Circuit arrows and weather tiles are both turned off by default and can be turned on using the Grafana options panel.
=> Circuit Arrows Turned Off and Added Weather Tiles To Map
